# Site settings
title: Stéphane Peter
email: megastep@megastep.org
url: https://stephanepeter.com
description: "Stéphane Peter: professional software developer for Catloaf Software, Codehost, Loki Software, and more."
locale: en_US
# To enable the Twitter Card features
twitter: 
  username: megastep
facebook:
  publisher: https://www.facebook.com/megastep
author:
  twitter: megastep
  picture: /img/profile.png
logo: /img/profile.png

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

exclude:
  - screenshot.png
  - README.md
  - LICENCE
  - CNAME

# Footer settings
footer:
  copyright: Stéphane Peter
  location: Snail Mail
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/megastep
  - title: facebook
    url: https://facebook.com/megastep
  - title: linkedin
    url: https://www.linkedin.com/in/stephanepeter
  - title: github
    url: https://github.com/megastep
  - title: stack-overflow
    url: https://stackoverflow.com/users/115287/megastep
  - title: youtube
    url: https://www.youtube.com/user/megastep
  - title: vimeo-square
    url: https://vimeo.com/megastep
  - title: soundcloud
    url: https://soundcloud.com/stephanepeter
  - title: lastfm
    url: https://www.last.fm/user/megascargot
  - title: instagram
    url: https://instagram.com/megastep/
  - title: tumblr
    url: https://megastep.tumblr.com/
  - title: medium
    url: https://medium.com/@megastep

# Postal address (add as many lines as necessary)
address:
  - line: P.O. Box 91506
  - line: Los Angeles, CA 90009
  - line: United States of America

analytics: UA-1803317-13

# Credits content
credits: 'Site based on the Freelancer Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: /section/:title/
highlighter: rouge

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from

